# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_Title', models.CharField(max_length=250)),
                ('Articles_Content', models.CharField(max_length=1000)),
                ('Article_Logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Title', models.CharField(max_length=250)),
                ('Event_Content', models.CharField(max_length=1000)),
                ('Event_Logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NewsAndUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NU_Title', models.CharField(max_length=250)),
                ('NU_Content', models.CharField(max_length=1000)),
                ('NU_Logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.CharField(max_length=250)),
                ('Project_Content', models.CharField(max_length=1000)),
                ('Project_Logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
