# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170623_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Articles_Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_Content',
            field=models.TextField(),
        ),
    ]
