# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170623_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Articles_Content',
            new_name='Article_Content',
        ),
    ]
