# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170625_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandupdate',
            name='NU_Posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
