# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170626_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandupdate',
            name='NU_Logo',
            field=models.FileField(upload_to=''),
        ),
    ]
