# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170627_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandupdate',
            name='NU_Posted',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
