# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170627_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandupdate',
            name='NU_Content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
