# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20170628_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Name', models.CharField(max_length=1000)),
                ('M_Email', models.CharField(max_length=1000)),
                ('M_Message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='newsandupdate',
            name='NU_Poster',
            field=models.CharField(choices=[('Glenn Paul Gara', 'Glenn Paul Gara'), ('Isaiah Evans Villa Abrille', 'Isaiah Evans Villa Abrille'), ('Seth Jasper Napalit', 'Seth Jasper Napalit'), ('Neil Ivan Palacios', 'Neil Ivan Palacios'), ('Christine Joy Busalanan', 'Christine Joy Busalanan'), ('Jesmar James Rama', 'Jesmar James Rama'), ('Reno Marco Fandiño', 'Reno Marco Fandiño'), ('Quinn Ray Anthony Intrepido', 'Quinn Ray Anthony Intrepido'), ('Mark Kenneth Jimenez', 'Mark Kenneth Jimenez'), ('Arch Renzo Falconi', 'Arch Renzo Falconi'), ('Elven Earl Tsuruoka', 'Elven Earl Tsuruoka'), ('Nikko Tulang', 'Nikko Tulang'), ('Villa Abrille and Co.', 'TANOM Group'), ('Napalit and Co.', 'HALANG Group'), ('Palacios and Co.', 'Explore Davao Group')], default='Glenn Paul Gara', max_length=100),
        ),
    ]
