# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170807_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='M_File',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
