# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_message_m_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='M_File',
        ),
    ]
